/** Common frame colors for autocomplete — users can still type custom values. */
export const COLOR_SUGGESTIONS = [
  "Black",
  "Brown",
  "Gold",
  "Silver",
  "Gunmetal",
  "Tortoise",
  "Havana",
  "Red",
  "Blue",
  "Green",
  "Pink",
  "Purple",
  "Clear",
  "White",
  "Grey",
  "Gray",
  "Rose Gold",
  "Matte Black",
  "Shiny Black",
  "Crystal",
  "Demi",
  "Two-tone",
];
