// A curated list of common eyewear manufacturers / brands used to seed the
// autocomplete on the New / Edit Frame form. The user is never restricted to
// this list — they can always type a brand new value. The runtime suggestion
// list merges this with whatever distinct manufacturers actually exist in
// the database.
//
// To add/remove a brand: just edit this array. No migration needed.
export const COMMON_MANUFACTURERS: readonly string[] = [
  "Adidas",
  "Armani Exchange",
  "Bolle",
  "Bottega Veneta",
  "Brooks Brothers",
  "Bvlgari",
  "Calvin Klein",
  "Carrera",
  "Chanel",
  "Christian Dior",
  "Coach",
  "Costa Del Mar",
  "Diesel",
  "Dolce & Gabbana",
  "Emporio Armani",
  "Etnia Barcelona",
  "Fendi",
  "Fossil",
  "Gant",
  "Gentle Monster",
  "Giorgio Armani",
  "Givenchy",
  "Gucci",
  "Guess",
  "Hugo Boss",
  "Jimmy Choo",
  "Kate Spade",
  "Lacoste",
  "Lafont",
  "Lindberg",
  "Maui Jim",
  "Michael Kors",
  "Miu Miu",
  "Moscot",
  "Nike",
  "Oakley",
  "Oliver Peoples",
  "Persol",
  "Polo Ralph Lauren",
  "Prada",
  "Puma",
  "Quay Australia",
  "Ray-Ban",
  "Revo",
  "Saint Laurent",
  "Salvatore Ferragamo",
  "Serengeti",
  "Silhouette",
  "Smith",
  "Spy",
  "Tag Heuer",
  "Tiffany & Co.",
  "Tom Ford",
  "Tommy Hilfiger",
  "Tory Burch",
  "Under Armour",
  "Versace",
  "Vogue Eyewear",
  "Warby Parker",
  "Wiley X",
] as const;
